/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package denny;

/**
 *
 * @author User
 */
public class allison extends javax.swing.JFrame {

        int Litros=1,Detergente=1,Densidad=1,agua=1;
        double sales;
    /**
     * Creates new form allison
     */
    public allison() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        slLitros = new javax.swing.JSlider();
        slDetergente = new javax.swing.JSlider();
        slDensidad = new javax.swing.JSlider();
        lblLitros = new javax.swing.JLabel();
        lblDetergente = new javax.swing.JLabel();
        lblDensidad = new javax.swing.JLabel();
        lblAgua = new javax.swing.JLabel();
        lblSales = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        slLitros.setMajorTickSpacing(50);
        slLitros.setPaintLabels(true);
        slLitros.setPaintTicks(true);
        slLitros.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slLitrosStateChanged(evt);
            }
        });

        slDetergente.setMajorTickSpacing(50);
        slDetergente.setMaximum(10);
        slDetergente.setPaintLabels(true);
        slDetergente.setPaintTicks(true);
        slDetergente.setValue(5);
        slDetergente.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slDetergenteStateChanged(evt);
            }
        });

        slDensidad.setMajorTickSpacing(200);
        slDensidad.setMaximum(200);
        slDensidad.setMinimum(50);
        slDensidad.setPaintLabels(true);
        slDensidad.setPaintTicks(true);
        slDensidad.setValue(100);
        slDensidad.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slDensidadStateChanged(evt);
            }
        });

        lblLitros.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        lblDetergente.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        lblDensidad.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        lblAgua.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        lblSales.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(slLitros, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                        .addComponent(slDetergente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(slDensidad, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblLitros, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(lblDetergente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDensidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(lblAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(lblSales, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(slLitros, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLitros, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(slDetergente, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblDetergente, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(slDensidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDensidad, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAgua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSales, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void slLitrosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slLitrosStateChanged
        // TODO add your handling code here:
        Litros= slLitros.getValue();
        lblLitros.setText("Los litros son: " + Litros);
        agua=2*Litros+(Detergente/Densidad);
        sales=(double)(Detergente*Litros)/(100*Densidad);
        lblAgua.setText("La cantidad de agua es: " + agua);
        lblSales.setText("La cantidad de sales es: " + sales);
    }//GEN-LAST:event_slLitrosStateChanged

    private void slDetergenteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slDetergenteStateChanged
        // TODO add your handling code here:
        Detergente=slDetergente.getValue();
        lblDetergente.setText("EL detergente es: " + Detergente);
        agua=2*Litros+(Detergente/Densidad);
        sales=(double)(Detergente*Litros)/(100*Densidad);
        lblAgua.setText("La cantidad de agua es: " + agua);
        lblSales.setText("La cantidad de sales es: " + sales);
    }//GEN-LAST:event_slDetergenteStateChanged

    private void slDensidadStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slDensidadStateChanged
        // TODO add your handling code here:
        Densidad=slDensidad.getValue();
        lblDensidad.setText("La densidad es: " + Densidad);
        agua=2*Litros+(Detergente/Densidad);
        sales=(double)(Detergente*Litros)/(100*Densidad);
        lblAgua.setText("La cantidad de agua es: " + agua);
        lblSales.setText("La cantidad de sales es: " + sales);
    }//GEN-LAST:event_slDensidadStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(allison.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(allison.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(allison.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(allison.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new allison().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAgua;
    private javax.swing.JLabel lblDensidad;
    private javax.swing.JLabel lblDetergente;
    private javax.swing.JLabel lblLitros;
    private javax.swing.JLabel lblSales;
    private javax.swing.JSlider slDensidad;
    private javax.swing.JSlider slDetergente;
    private javax.swing.JSlider slLitros;
    // End of variables declaration//GEN-END:variables
}
